version: '3'

services:
  mongo-seed-video:
    image: mongo
    volumes:
    - .:/scripts
    command:
      'bash -c "mongoimport --jsonArray --drop --host database --db boat-mean --collection videos --type json --file /scripts/video.json"'
    depends_on: 
    - database