version: '3'

services:
  mongo-seed:
    image: mongo
    volumes:
    - .:/scripts
    command:
      'bash -c "mongoimport --jsonArray --drop --host database --db boat-mean --collection users --type json --file /scripts/user.json"'
    depends_on: 
    - database